#!/usr/bin/env bash

args=()
flags=()

from=( "${@:(($#-1)):1}" )
to=( "${@:$#}" )
paths=( "${@:1:(($# - 2))}" )

for path in "${paths[@]}"; do
  if [ "${path::1}" != '-' ]; then

    for path in $(dir-tree "$path"); do
      args+=("--include=$path")
    done

    args+=("--include=$path/**")
  else
    flags+=("$path")
  fi
done

echo "Running:"
echo rsync -avzh "${flags[@]}" "${args[@]}" --exclude='*' "${from[@]}" "${to[@]}"
rsync -avzh "${flags[@]}" "${args[@]}" --exclude='*' "${from[@]}" "${to[@]}"
